# frozen_string_literal: true

source "https://rubygems.org"

# gem "cutter", git: "git@github.com:solehudinmq/cutter.git", branch: "main"
gem "cutter", path: "../" # for test in localhost
gem "byebug"
gem "activerecord"
gem "sqlite3"
