# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "cutter", git: "git@github.com:solehudinmq/cutter.git", branch: "main"
# gem "cutter", path: "../cutter" # for test in localhost
gem "byebug"
gem "sinatra"
gem "activerecord"
gem "sqlite3"
gem "httparty"
gem "rackup", "~> 2.2"
gem "puma", "~> 7.1"
